### ISSUE TITLE
Possibility to change section name

### ISSUE THREAD

**Issue by denizzzka** [burner/inifiled#1]
How I can change section name to any human-readable form?

Example (name in result ini-file is "const(config.Config)"):

``` d
import inifiled;


@INI("Main section")
private struct Config {
    @INI("The lastname of the Person") string lastname;

    @INI("The height of the Person") float height;

    @INI("Some strings with a very long long INI description that is longer" ~
        " than eigthy lines hopefully."
    ) string[] someStrings;
}

const Config cfg;

static this()
{
    cfg.lastname = "test name";

    writeINIFile(cfg, "config.conf");
}
```

``` ini
$ cat config.conf 
; Main section
[const(config.Config)]
; The lastname of the Person
lastname="test name"
; The height of the Person
height="nan"
; Some strings with a very long long INI description that is longer than eigthy
;  lines hopefully.
someStrings=""
```

**Comment by denizzzka** [comment]
in "const(config.Config)" "config" is module name (derrived from filename config.d)

**Comment by burner** [comment]
have a look at getTypeName

**Comment by denizzzka** [comment]
still do not understand

i want to get something like "MainSection"

**Comment by burner** [comment]
const is part of the type, const int, is not a const int it is a const(int).

**Comment by denizzzka** [comment]
I want section name not generated from source because fully qualified name isn't controlled by me. I.e.:

const(config.Config)

const - can be removed, ok
config - module name. It always available while compiling, it can't be removed
Config - my struct name (only this really controlled by coder)

My target is obtain section name like [SectionStructName]. Now I can get only: [someModuleName.SectionStructName]

**Comment by burner** [comment]
than you have to change the lines around https://github.com/burner/inifiled/blob/master/source/inifiled.d#L337

**Comment by denizzzka** [comment]
and same with reading... I still can not understand how achieve this challenge. can you write example string?

**Comment by burner** [comment]
if you have [someModuleName.SectionStructName] just slice the string. I dont see what problem you have

**Comment by denizzzka** [comment]
It seems that we are talking about different things. And perhaps I misunderstood principle.

The system automatically creates a name for the section, right?
I pass a struct with INTs to writeINIFile(..): "this is a section, write it to a file, please!", right?

How to specify name of the section in this case if the Inifiled's writeINIFile takes section name from the name of a struct with module name (and modifiers if they are specified)?
(I am talking only about recording, not about reading.)

**Comment by burner** [comment]
inifile.d does not have that feature. It will always take the fully qualified typename as the section name

**Comment by denizzzka** [comment]
> fully qualified typename as the section name

why?

**Comment by burner** [comment]
because, I wanted to know what types the following values belong to

**Comment by denizzzka** [comment]
What if the name of the section will be a pure name of the structure?

**Comment by burner** [comment]
that is possible. will you create the PR.

**Comment by denizzzka** [comment]
Perhaps, if it isn't break other stuff

**Comment by burner** [comment]
Unqual should do the job
