### ISSUE TITLE
debugLogs should not be the default

### ISSUE THREAD

**Issue by andre2007** [burner/inifiled#13]
I just created an issue for DScanner https://github.com/dlang-community/D-Scanner/issues/612
but I think the issue is located in inifiled.
The debug logs which are on by default causes an issue with the json output. It destroys the schema of the json.
It would be great if the debug logs are off by default. In most cases the users of your  library might not want to have stdout written. Could you check?

**Comment by andre2007** [comment]
Pull request #14

**Comment by burner** [comment]
fixed in 1.3.1
