### ISSUE TITLE
string[] values isn't stored by writeINIFile(..)

### ISSUE THREAD

**Issue by denizzzka** [burner/inifiled#2]
``` d
@INI("Main section")
private struct Config {
    @INI("la")
    string[] listen_addresses = [":::60180\"", "asd"];
}
```

``` ini
; Main section
[const(config.Config)]
; la
listen_addresses=":::60180",asd"
```

however, I do not know what is the "proper way" in this case...

**Comment by burner** [comment]
:::60180 has an extra \" on it that's passed to the ini file

**Comment by denizzzka** [comment]
> :::60180 has an extra \" on it that's passed to the ini file

isn't extra - expressly

**Comment by burner** [comment]
no a value has the grammar "[a-Z](,[a-Z])*" a-Z includes basically all but "

if you another double tick the parser thinks it is the end of the value. because the first double tick starts the value and the next terminates it
