### ISSUE TITLE
callback to handle changes in a structure

### ISSUE THREAD

**Issue by ghost** [burner/inifiled#7]
Let's say a `@INI` structure is modified, for example from

``` D
@INI("A Dog")
struct Dog {
    @INI("The name of the Dog") string name;
}
```

to  

``` D
@INI("A Dog")
struct Dog {
    @INI("The name of the Dog") string[] name;
}
```

Nothing happens if I save with the old declaration and reload with the new but it would be useful to have an otpional user callback in  `readINIFile()` to handle the convertion from the value read to the new type. This is a typical case that should be handled by a serializer.

**Comment by burner** [comment]
I'm open to pull requests
