### ISSUE TITLE
Building Failing for Release

### ISSUE THREAD

**Issue by skl131313** [burner/inifiled#8]
Some imports are debug only but are needed even when the build isn't a debug build.

Change:
https://github.com/burner/inifiled/commit/f6886e0521d18441b49ab3a22b255b72c8c56025#diff-82064d7e33901fac19a46b173acf65a9R226

https://github.com/burner/inifiled/blob/master/source/inifiled.d#L238

**Comment by burner** [comment]
should be fixed with 1.0.1

**Comment by burner** [comment]
feel free to reopen if not
